import { createContext, useContext, useEffect, useState } from 'react';
import api from '../api/client';
const Ctx = createContext(null);
export const AuthProvider = ({children})=>{ const [user,setUser]=useState(null);
  const login = async (email,password)=>{ const {data}=await api.post('/auth/login',{email,password}); localStorage.setItem('token',data.token); setUser(data.user); };
  const register = async (name,email,password)=>{ const {data}=await api.post('/auth/register',{name,email,password}); localStorage.setItem('token',data.token); setUser(data.user); };
  const logout = ()=>{ localStorage.removeItem('token'); setUser(null); };
  useEffect(()=>{ if(localStorage.getItem('token')) api.get('/auth/me').then(({data})=>setUser(data)).catch(logout); },[]);
  return <Ctx.Provider value={{user,login,register,logout}}>{children}</Ctx.Provider>; };
export const useAuth=()=>useContext(Ctx);
