import { Navigate, Link, Route, Routes } from 'react-router-dom';
import { useEffect, useMemo, useState } from 'react';
import { motion } from 'framer-motion';
import { io } from 'socket.io-client';
import api from './api/client';
import { useAuth } from './context/AuthContext';

const Layout = ({ children }) => {
  const { user, logout } = useAuth();
  return <div className='min-h-screen'><nav className='border-b border-slate-800 p-3 flex gap-3'>{user && <><Link to='/dashboard'>Dashboard</Link><Link to='/quiz'>Quiz</Link><Link to='/flashcards'>Flashcards</Link><Link to='/roadmap'>Roadmap</Link><Link to='/coding'>Coding</Link><Link to='/ai'>AI Tutor</Link><Link to='/study'>Study Room</Link><Link to='/notes'>Notes</Link><Link to='/admin'>Admin</Link><button onClick={logout}>Logout</button></>} </nav><main className='max-w-6xl mx-auto p-4'>{children}</main></div>;
};

const AuthPage = () => { const { login, register } = useAuth(); const [loginMode,setLoginMode]=useState(true); const [form,setForm]=useState({name:'',email:'',password:''});
  return <div className='card max-w-md mx-auto space-y-2'><h1 className='text-2xl'>{loginMode?'Login':'Register'}</h1>{!loginMode&&<input className='w-full bg-slate-800 p-2' placeholder='name' onChange={e=>setForm({...form,name:e.target.value})}/>}<input className='w-full bg-slate-800 p-2' placeholder='email' onChange={e=>setForm({...form,email:e.target.value})}/><input type='password' className='w-full bg-slate-800 p-2' placeholder='password' onChange={e=>setForm({...form,password:e.target.value})}/><button className='bg-violet-600 px-3 py-2 rounded' onClick={()=>loginMode?login(form.email,form.password):register(form.name,form.email,form.password)}>Continue</button><button onClick={()=>setLoginMode(!loginMode)}>Switch</button></div>;
};

const Dashboard = () => { const { user } = useAuth(); const [leaders,setLeaders]=useState([]); useEffect(()=>{api.get('/leaderboard').then(r=>setLeaders(r.data));},[]); if(!user) return null; const pct=((user.xp%250)/250)*100;
  return <div className='space-y-3'><div className='grid md:grid-cols-3 gap-3'><div className='card'>XP {user.xp}</div><div className='card'>Level {user.level}</div><div className='card'>Streak {user.dailyStreak}</div></div><div className='card'><div className='h-2 bg-slate-800 rounded'><div className='h-2 bg-violet-500 rounded' style={{width:`${pct}%`}}/></div></div><div className='card'>{leaders.map((l,i)=><div key={l._id}>{i+1}. {l.name} - {l.xp}</div>)}</div></div>;
};

const Quiz = ()=>{ const [quiz,setQuiz]=useState(); const [answers,setAnswers]=useState({}); const [result,setResult]=useState(); useEffect(()=>{api.get('/quizzes').then(r=>setQuiz(r.data[0]));},[]); if(!quiz) return 'Loading'; return <div className='space-y-2'><h2>{quiz.title}</h2>{quiz.questions.map((q,qi)=><div className='card' key={q._id}><p>{q.prompt} ({q.timeLimitSec}s)</p>{q.options.map((o,oi)=><button key={o} className='block bg-slate-800 rounded p-2 mt-1' onClick={()=>setAnswers({...answers,[qi]:oi})}>{o}</button>)}</div>)}<button className='bg-violet-600 px-3 py-2 rounded' onClick={async()=>setResult((await api.post(`/quizzes/${quiz._id}/submit`,{answers})).data)}>Submit</button>{result&&<div className='card'>Score {result.score}/{result.total}, XP +{result.xpEarned}</div>}</div>; };

const Flashcards = ()=>{ const [deck,setDeck]=useState(); const [i,setI]=useState(0); const [flip,setFlip]=useState(false); useEffect(()=>{api.get('/flashcards').then(r=>setDeck(r.data[0]));},[]); if(!deck) return 'Loading'; const c=deck.cards[i]; return <div><motion.div whileHover={{scale:1.02}} onClick={()=>setFlip(!flip)} className='card min-h-36 cursor-pointer text-xl'>{flip?c.back:c.front}</motion.div><button onClick={()=>{setI(Math.min(deck.cards.length-1,i+1));setFlip(false);}}>Next</button></div>; };

const Roadmap=()=>{ const [nodes,setNodes]=useState([]); const [next,setNext]=useState(''); useEffect(()=>{api.get('/roadmap').then(r=>setNodes(r.data));},[]); return <div>{nodes.map(n=><button className='card block w-full text-left mb-2' key={n._id} onClick={async()=>{const r=await api.post(`/roadmap/${n._id}/complete`);setNext(r.data.nextSuggested?.title||'Done');}}>{n.title}</button>)}{next&&<p>Suggested: {next}</p>}</div>; };
const Coding=()=>{ const [code,setCode]=useState('function sum(a,b){ return a - b; }'); const [msg,setMsg]=useState(''); const hints=['Check operator','Use +','Replace a-b with a+b']; const [h,setH]=useState(0); return <div className='space-y-2'><textarea className='w-full h-40 bg-slate-900 p-2' value={code} onChange={e=>setCode(e.target.value)} /><button onClick={()=>setMsg(code.includes('a + b')?'PASS':'FAIL')} className='bg-violet-600 px-3 py-2 rounded'>Run tests</button><button className='ml-2' onClick={()=>setH(Math.min(2,h+1))}>Hint</button><p>{msg}</p><p>{hints[h]}</p></div>; };
const AI=()=>{ const [q,setQ]=useState('Explain recursion'); const [a,setA]=useState(''); return <div><input className='bg-slate-800 p-2 w-full' value={q} onChange={e=>setQ(e.target.value)} /><button className='bg-violet-600 px-3 py-2 rounded mt-2' onClick={async()=>setA((await api.post('/ai/tutor',{question:q,context:'coding'})).data.answer)}>Ask</button><div className='card mt-2'>{a}</div></div>; };
const Notes=()=>{ const [notes,setNotes]=useState([]); const [title,setTitle]=useState(''); const [markdown,setMarkdown]=useState(''); const load=()=>api.get('/notes').then(r=>setNotes(r.data)); useEffect(load,[]); return <div className='grid md:grid-cols-2 gap-3'><div className='card'><input className='w-full bg-slate-800 p-2 mb-2' value={title} onChange={e=>setTitle(e.target.value)} placeholder='Title'/><textarea className='w-full h-44 bg-slate-800 p-2' value={markdown} onChange={e=>setMarkdown(e.target.value)} /><button className='bg-violet-600 px-3 py-2 rounded mt-2' onClick={async()=>{await api.post('/notes',{title,markdown});setTitle('');setMarkdown('');load();}}>Save</button></div><div className='card'>{notes.map(n=><div key={n._id}><b>{n.title}</b><div className='text-xs'>{n.keywords?.join(', ')}</div></div>)}</div></div>; };
const Admin=()=>{ const [s,setS]=useState(); useEffect(()=>{api.get('/admin/stats').then(r=>setS(r.data));},[]); return <div className='grid md:grid-cols-2 gap-3'>{s&&Object.entries(s).map(([k,v])=><div className='card' key={k}>{k}: {v}</div>)}</div>; };
const Study=()=>{ const { user } = useAuth(); const socket = useMemo(()=>io(import.meta.env.VITE_SOCKET_URL||'http://localhost:5000'),[]); const [room,setRoom]=useState('GLOBAL'); const [text,setText]=useState(''); const [messages,setMessages]=useState([]); useEffect(()=>{socket.emit('room:join',{roomCode:room,username:user?.name||'Guest'}); socket.on('room:message',m=>setMessages(v=>[...v,m])); return ()=>socket.disconnect();},[room]); return <div><input className='bg-slate-800 p-2' value={room} onChange={e=>setRoom(e.target.value.toUpperCase())}/><div className='card h-48 overflow-auto my-2'>{messages.map((m,i)=><p key={i}>{m.user}: {m.text}</p>)}</div><input className='bg-slate-800 p-2' value={text} onChange={e=>setText(e.target.value)}/><button className='ml-2 bg-violet-600 px-3 py-2 rounded' onClick={()=>{socket.emit('room:chat',{roomCode:room,user:user?.name,text});setText('');}}>Send</button></div>; };

const Private = ({children})=> useAuth().user ? children : <Navigate to='/auth' replace/>;

export default function App(){ return <Layout><Routes><Route path='/auth' element={<AuthPage/>}/><Route path='/' element={<Navigate to='/dashboard'/>}/><Route path='/dashboard' element={<Private><Dashboard/></Private>}/><Route path='/quiz' element={<Private><Quiz/></Private>}/><Route path='/flashcards' element={<Private><Flashcards/></Private>}/><Route path='/roadmap' element={<Private><Roadmap/></Private>}/><Route path='/coding' element={<Private><Coding/></Private>}/><Route path='/ai' element={<Private><AI/></Private>}/><Route path='/study' element={<Private><Study/></Private>}/><Route path='/notes' element={<Private><Notes/></Private>}/><Route path='/admin' element={<Private><Admin/></Private>}/></Routes></Layout>; }
